spring.application.name=currency-service

server.port=8100

spring.datasource.url=jdbc:postgresql://localhost/db_currency
spring.datasource.username=postgres
spring.datasource.password=Markus11997

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.locations=classpath:db_migration