spring.application.name=greeting-service
server.port=8081

greeting-service.greeting=Hello
greeting-service.default-name=World

spring.profiles.active=it

# =========================================================
# SERVICE REGISTRY - EUREKA
# =========================================================

# URL do servidor Eureka para self registration
eureka.client.service-url.default-zone=http://localhost:8761/eureka

# Faz o Eureka registrar o IP da máquina ao invés do hostname
# Ideal para ambientes containerizados
eureka.instance.prefer-ip-address=true

# Personaliza o ID da instância no Eureka
# Exemplo: currency-service:8100
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Habilita health check do Actuator no Eureka
eureka.client.healthcheck.enabled=true

# Metadata personalizada exibida no Eureka
# Informando o repositório Git do projeto
eureka.instance.metadata-map.github.repo=tino-navarro/microservices-java


# =========================================================
# SPRING ACTUATOR / MONITORAMENTO
# =========================================================

# Endpoints expostos pelo Actuator
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events

# Exibe detalhes completos da saúde da aplicação
management.endpoint.health.show-details=always

# Habilita leitura das propriedades info.*
management.info.env.enabled=true

# Habilita probes de readiness/liveness
management.endpoint.health.probes.enabled=true

# Mantém health indicators padrão ativos
management.health.defaults.enabled=true


# =========================================================
# ENDPOINT /ACTUATOR/INFO
# =========================================================

# Nome da aplicação exibido no /actuator/info
info.app.name=${spring.application.name}

# Descrição do microsserviço
info.app.description=Microsservico onde retorna boas vindas ao usuario cadastrado

# Nome do autor/aluno
info.app.autor=Tino Markus Bueno Navarro