spring.application.name=product-service

server.port=8101

spring.datasource.url=jdbc:postgresql://localhost/bd_product
spring.datasource.username=postgres
spring.datasource.password=Markus11997

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.locations=classpath:db_migration