spring.application.name=product-service

server.port=8000

spring.datasource.url=jdbc:postgresql://localhost/bd_product
spring.datasource.username=postgres
spring.datasource.password=Markus11997

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.locations=classpath:db_migration

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events

management.endpoint.health.show-details=always

management.info.env.enabled=true

management.endpoint.health.probes.enabled=true

management.health.defaults.enabled=true