spring.application.name=product-service

server.port=8000

spring.datasource.url=jdbc:postgresql://localhost/bd_product
spring.datasource.username=postgres
spring.datasource.password=Markus11997

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.locations=classpath:db_migration

# =========================================================
# SERVICE REGISTRY - EUREKA
# =========================================================

# URL do servidor Eureka para self registration
eureka.client.service-url.default-zone=http://localhost:8761/eureka

# Faz o Eureka registrar o IP da máquina ao invés do hostname
# Ideal para ambientes containerizados
eureka.instance.prefer-ip-address=true

# Personaliza o ID da instância no Eureka
# Exemplo: currency-service:8100
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Habilita health check do Actuator no Eureka
eureka.client.healthcheck.enabled=true

# Metadata personalizada exibida no Eureka
# Informando o repositório Git do projeto
eureka.instance.metadata-map.github.repo=tino-navarro/microservices-java


# =========================================================
# SPRING ACTUATOR / MONITORAMENTO
# =========================================================

# Endpoints expostos pelo Actuator
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events

# Exibe detalhes completos da saúde da aplicação
management.endpoint.health.show-details=always

# Habilita leitura das propriedades info.*
management.info.env.enabled=true

# Habilita probes de readiness/liveness
management.endpoint.health.probes.enabled=true

# Mantém health indicators padrão ativos
management.health.defaults.enabled=true


# =========================================================
# ENDPOINT /ACTUATOR/INFO
# =========================================================

# Nome da aplicação exibido no /actuator/info
info.app.name=${spring.application.name}

# Descrição do microsserviço
info.app.description=Microsservico responsavel pela busca dos produtos na base e o retorno das mesmas com valores convertidos

# Nome do autor/aluno
info.app.autor=Tino Markus Bueno Navarro

# RESILIENCE PATTERNS - TIMEOUT
# Timeout para estabelecer conexão (1 segundo)
spring.cloud.openfeign.client.config.currency-service.connect-timeout=1000
# Timeout para processar e receber os dados (3 segundos)
spring.cloud.openfeign.client.config.currency-service.read-timeout=3000

# RESILIENCE PATTERNS - RETRY
# Quantidade máxima de tentativas (primeira + 2 tentativas)
resilience4j.retry.instances.currency-service.max-attempts=3
# Tempo de espera inicial entre as tentativas
resilience4j.retry.instances.currency-service.wait-duration=500ms
# Ativa o recuo exponencial (Exponencial Backoff)
resilience4j.retry.instances.currency-service.enable-exponential-backoff=true
# Multiplicador do tempo de espera (Tentativa 1: 500ms -> Tentativa 2: 500x2 = 1000ms)
resilience4j.retry.instances.currency-service.exponential-backoff-multiplier=2.0
# Ativa variação aleatória do tempo de espera (Jitter)
resilience4j.retry.instances.currency-service.enable-randomized-wait=true
# Fator do Jitter (Aplica uma flutuação aleatório de até 50% para mais ou menos)
resilience4j.retry.instances.currency-service.randomized-wait-factor=0.5

# RETENTAR (foca apenas em falhas transitórias e instabilidades)
# Retenta em caso de timeout controlado pelo OpenFeign
resilience4j.retry.instances.currency-service.retry-exceptions[0]=feign.RetryableException
# Retenta em caso de queda drástica de socket/rede pura
resilience4j.retry.instances.currency-service.retry-exceptions[1]=java.net.SocketTimeoutException
# Retenta em caso de erros HTTP da familia 5xx vindo do servidor(500, 502, 503, 504, etc)
resilience4j.retry.instances.currency-service.retry-exceptions[2]=feign.FeignException\$FeignServerException

# RESILIENCE PATTERNS - CACHING
# Configura o tipo de cache. Para cache em memória o caffeine é considerado com melhor desempenho
spring.cache.type=caffeine
# Configurações do cache:500 objetos no máximo e com um tempo de expiração de 15 segundos
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=15s

# RESILIENCE PATTERNS - CIRCUIT BREAKER
# habilita o Circuit Breaker do Resilience4j no OpenFeign
spring.cloud.openfeign.circuitbreaker.enabled=true
# Habilita o indicador de saude para esta instancia do circuit breaker
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.register-health-indicator=true
# Numero de chamadas na janela deslizante para calcular a taxa de falhas
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.sliding-window-size=10
# Numero minimo de chamadas antes de calcular a taxa de falhas
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.minimum-number-of-calls=5
# Percentual maximo de falhas permitido antes de abrir o circuito
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.failure-rate-threshold=50
# Tempo que o circuito permanece aberto antes de ir para meio-aberto
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.wait-duration-in-open-state=30s
# Numero de chamadas permitidas no estado meio-aberto para testar
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.permitted-number-of-calls-in-half-open-state=3
# Ativa a transicao automatica de aberto para meio-aberto sem esperar chamada
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.automatic-transition-from-open-to-half-open-enabled=true

# Habilita o actuator monitorar a saúde em conjunto com o circuit breaker
management.health.circuitbreakers.enabled=true

# Faz o OpenFeign usar o nome do microserviço como ID
# dessa forma sincroniza o retry com o circuit breaker
spring.cloud.openfeign.circuitbreaker.group.enabled=true