spring.application.name=config-service
server.port=8888

#spring.profiles.active=native

#spring.cloud.config.server.native.search-locations=classpath:/configs/{application}

spring.cloud.config.server.git.uri=https://github.com/tino-navarro/microservices-java.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=/microservices/configs/{application}