spring.application.name=config-service
server.port=8888

#spring.profiles.active=native

#spring.cloud.config.server.native.search-locations=classpath:/configs/{application}

spring.cloud.config.server.git.uri=https://github.com/tino-navarro/microservices-java.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=/microservices/configs/{application}

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events

management.endpoint.health.show-details=always

management.info.env.enabled=true

management.endpoint.health.probes.enabled=true

management.health.defaults.enabled=true